version: "3.3"
services:
  demo7:
    depends_on:
      - ros
    build:
      context: .
    container_name: cmput412_demo7_container
    tty: true
    stdin_open: true
    privileged: true
    environment:
      DISPLAY: ":0"
      ROS_IP: 127.0.0.1
      QT_X11_NO_MITSHM: 1
      PYTHONPATH: /opt/ros/kinetic/lib/python2.7/dist-packages
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "$XAUTHORITY:/root/.Xauthority"
      - ".:/source"
  ros:
    build:
      context: .
      dockerfile: ros.Dockerfile
